services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c hba_file=/var/lib/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cars" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  prometheus:
#    image: prom/prometheus:latest
#    ports:
#      - "9090:9090"
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#    volumes:
#      - ./monitor/prometheus.yaml:/etc/prometheus/prometheus.yml

#  grafana:
#    image: grafana/grafana
#    restart: unless-stopped
#    ports:
#      - "3001:3000"
#    volumes:
#      - grafana-storage:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      db:
        condition: service_healthy
  
#volumes:
#  grafana-storage: {}